name: sync_upstream
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '39 12,19 * * 1-5'
  workflow_dispatch: # on button click
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100 
          token: ${{ secrets.VUL_DRILLER_TOKEN }}
      - name: config
        run: |
          git config --global user.name 'certcc-ghbot'
          git config --global user.email 'cert+ghbot@cert.org'
      - name: fetch upstream
        run: |
          git remote add upstream ${{ vars.UPSTREAM_URL }}
          git fetch upstream
      - name: delete tags
        run: |
          git tag -d $(git tag -l "20*")
          git tag -d $(git tag -l "4*")
          git tag -d $(git tag -l "5*")
          git tag -d $(git tag -l "6*")
          git tag -d $(git tag -l "sprint*")
          git tag -d $(git tag -l "blog*")
          git tag -d $(git tag -l "v4*")
          git tag -d $(git tag -l "show*")
          git tag -d $(git tag -l "cth*")
          git tag -d $(git tag -l "hard*")
      - name: merge and push
        run: |
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
